Create Website for Capstone Project
MosDevx/web-dev-capstone pull request #2
Opened 2022-10-21 21:23 UTC by MosDevx

Create mobile and Desktop versions of website
Dynamically generated of speakers
Add assets;images, icons , datastore
Add show more button to display more speakers on mobile

2022-10-21 21:47 UTC, vickymarz requested changes
Hi @MosDevx, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project, that does not have a video presentation. Kindly add your video presentation to your PR summary and submit it again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-21 22:16 UTC, vickymarz requested changes
Hi @MosDevx, 

Good job so far! 🤝 
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes

- [ ] The duration for the loom video recording is 5min but you made your presentation in less than 2min which means you didn't tell us more about the project. Kindly do a more detailed video presentation 👍🏽 

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-10-21 22:16 UTC, vickymarz commented on src/Js/homepage.js
> +async function getSpeakerList() {
- [ ] Your list of speakers seems not to display on the page load unless I refresh the page. Kindly ensure that when the page loads, the featured speakers get rendered to the UI at once 👍🏽 

![image](https://user-images.githubusercontent.com/63473584/197295361-ddb9e793-6356-4952-b67e-a88bd9e2a2ec.png)

2022-10-21 22:16 UTC, vickymarz commented on README.md
>  > Capstone Project for Module 1 of Microverse
- [ ] I will strongly recommend you write a more detailed description of your project so that recruiters or anyone will understand firsthand what the project is all about which will make your repo look professional 😄

2022-10-21 22:16 UTC, vickymarz commented on src/about.html
> +				<!-- <a href="" class="p-1 text-primary-orange ring ring-primary-orange">CC Campaign</a> -->
- [ ] Kindly ensure you dont leave any commented code in your codebase so that your codebase will be clean and readable 👍🏽

2022-10-22 11:20 UTC, MosDevx commented on src/Js/homepage.js
> +async function getSpeakerList() {
@vickymarz I wasn't able to recreate this issue but I added new functionality that takes into account screen resizing.Thanks for the review

2022-10-22 14:16 UTC, Tadesse-Alemayehu requested changes
### Hi @MosDevx , 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost-done-ashley-garcia](https://user-images.githubusercontent.com/69077061/197343999-32bb05b7-0d74-40ea-82d1-95f865d60729.gif)


 ## Highlights
 - [x] Good job overall following the template design 💯
 - [x]  Correct GitHub Flow 👍🏾
 - [x] Good commit history 🥇
 - [x] Good PR title/description 💯
 - [x] All linters passed 🥇

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-22 14:16 UTC, Tadesse-Alemayehu commented on src/Js/homepage.js
> +showButton.addEventListener('click', () => {
- [ ] Good job addressing some of the requirement suggested by previous reviewer. There is an issue when you try to `appendChild` and `addEventListener`, Hence our feature speakers are not displayed on the main page. This ia one of the main requirements. 

https://user-images.githubusercontent.com/69077061/197343707-dfaa1c42-1b2b-4635-9605-2eebaa01f9f8.mp4

2022-10-22 14:31 UTC, MosDevx commented on src/Js/homepage.js
> +showButton.addEventListener('click', () => {
@Tadesse-Alemayehu  Ive tried loading this site on a number of different devices and i get no error. Even on my video i used th elive demo link and it loaded the data. I dont know how to recreate this issue or how to fix it at this point

2022-10-22 14:38 UTC, Tadesse-Alemayehu commented on src/Js/homepage.js
> +showButton.addEventListener('click', () => {
Dear @MosDevx. I know this is weird. I just tried it now again. the thing is it works on the first load and not anymore after that.

2022-10-22 14:42 UTC, Tadesse-Alemayehu commented on src/Js/homepage.js
> +showButton.addEventListener('click', () => {
It seems to be working now. Try it with an incognito tab and ask for a review. Good luck ✌

2022-10-22 14:49 UTC, Tadesse-Alemayehu approved these changes
### Hi @MosDevx 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![68747470733a2f2f6669636f666f72756d732e6d796669636f2e636f6d2f74352f696d6167652f736572766572706167652f696d6167652d69642f343932363069463839303835363833444139334135422f696d6167652d73697](https://user-images.githubusercontent.com/69077061/197345542-d53bd541-ad55-4b84-b510-7bea8038c984.gif)

## Highlights
 - [ ] Good job overall following the template design 💯
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-22 14:57 UTC, merged